version: '3'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      - ENDPOINT=http://backend:9001/api
    volumes:
      - ./frontend:/app
    command: npm start

  backend:
    build:
      context: ./backend
    ports:
      - "9001:9001"
    environment:
      - APPID=cd48225572f420a5d0619a255c3488f4
      - MAP_ENDPOINT=http://api.openweathermap.org/data/2.5
      - TARGET_CITY=Helsinki,fi
    volumes:
      - ./backend:/app
    command: npm start
