version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "9000:9000"
    environment:
      - API_KEY=cd48225572f420a5d0619a255c3488f4
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_KEY=cd48225572f420a5d0619a255c3488f4
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start
