---
- name: Copy Docker Compose file
  copy:
    src: /eficode-recriutment-2024/docker-compose.yml
    dest: /app/docker-compose.yml

- name: Ensure Docker Compose is installed
  pip:
    name: docker-compose
    state: present

- name: Pull Docker images and start containers
  command: docker-compose up -d
  args:
    chdir: /path/on/remote/host/
